### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by brentm5** [tklein/windirstat-cookbook#2]
Are you going to release version 1.0.1 to fix the issue with the metadata.json file?  Converges have been failing

**Comment by brentm5** [comment]
Any word on this?  Also if you don't want to maintain this I don't mind pitching in if you want to add me as a contributer

**Comment by tklein** [comment]
Sorry for replying that late, was a bit too busy.
I'm going to release the new version latest tomorrow.

**Comment by tklein** [comment]
New release uploaded to the Supermarket.

Sorry for being late...

**Comment by brentm5** [comment]
Thanks! Just saw it.
